apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dca-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dca-backend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50    # ✅ CPU 50% 이상이면 스케일 아웃
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0   # 🚀 즉시 반응
      selectPolicy: Max
      policies:
        - type: Pods
          value: 3                     # 한 번에 최대 +3개 허용 (1→4 점프 가능)
          periodSeconds: 15
        - type: Percent
          value: 200                   # 200% 증가까지 허용
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300  # ⏬ 줄일 때는 5분 관찰 후
      selectPolicy: Min
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60