apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dca-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dca-backend
  minReplicas: 4    # 최소 4개 유지
  maxReplicas: 10   # 최대 10개까지 증가 가능
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # CPU 50% 이상이면 스케일 아웃
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50   # 메모리 50% 이상이면 스케일 아웃