apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dca-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dca-backend
  minReplicas: 1          # ✅ 최소 1개
  maxReplicas: 4          # ✅ 최대 4개
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # ✅ CPU 사용률 50% 이상이면 증설
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50   # ✅ 메모리 사용률 50% 이상이면 증설