apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
  namespace: dev
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
        scenarios: {
            light_test: {
                executor: 'ramping-vus',
                startVUs: 0,
                stages: [
                    { duration: '10s', target: 1 },
                ],
                gracefulRampDown: '0s',
            },
        },
    };

    export default function () {
        http.post(
            'http://dca-backend.default.svc.cluster.local:8080/backend/api/play',
            null,
            { headers: { 'Content-Type': 'application/json' } }
        );
        sleep(1);
    }