apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
  namespace: default
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
        scenarios: {
            heavy_test: {
                executor: 'ramping-vus',
                startVUs: 0,
                stages: [
                    { duration: '30s', target: 10 },   // 30초 동안 10 VU까지 ramp-up
                    { duration: '1m', target: 10 },    // 1분 동안 10 VU 유지
                    { duration: '30s', target: 20 },   // 30초 동안 20 VU까지 증가
                    { duration: '1m', target: 20 },    // 1분 동안 20 VU 유지
                    { duration: '30s', target: 0 },    // 부드럽게 내려옴
                ],
                gracefulRampDown: '10s',
            },
        },
    };

    export default function () {
        http.post(
            'http://dca-backend.default.svc.cluster.local:8080/backend/api/play',
            null,
            { headers: { 'Content-Type': 'application/json' } }
        );
        sleep(1);
    }