apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-scripts
  namespace: default
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export const options = {
      vus: 10,
      duration: '30s',
    };

    export default function () {
      const res = http.get('http://dca-backend:8080/backend/api/play');
      check(res, { 'status was 200': (r) => r.status === 200 });
      sleep(1);
    }
