apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
  namespace: default
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
        scenarios: {
            heavy_test: {
                executor: 'ramping-vus',
                startVUs: 0,
                stages: [
                    { duration: '15s', target: 5 },   // 30초 동안 10 VU까지 ramp-up
                    { duration: '30s', target: 15 },    // 1분 동안 10 VU 유지
                    { duration: '45s', target: 20 },   // 30초 동안 20 VU까지 증가
                    { duration: '30s', target: 10 },    // 1분 동안 20 VU 유지
                    { duration: '15s', target: 0 },    // 부드럽게 내려옴
                ],
                gracefulRampDown: '10s',
            },
        },
        tags: {
            testid: __ENV.JOB_NAME || "manual-test"  // Job에서 전달된 이름으로 라벨링
        },
    };

    export default function () {
        const url = 'http://dca-backend.default.svc.cluster.local:8080/backend/api/play';
        const headers = { 'Content-Type': 'application/json' };

        const res = http.post(url, null, { headers });
        
        // 응답 상태 코드 기록
        if (res.status !== 200) {
            console.error(`Request failed. Status: ${res.status}`);
        }

        sleep(1);
    }