apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
data:
  test.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
        scenarios: {
            ramping_test: {
                executor: 'ramping-vus',
                startVUs: 0,
                stages: [
                    { duration: '30s', target: 5 },
                    { duration: '1m', target: 10 },
                    { duration: '30s', target: 0 },
                ],
            },
        },
    };

    export default function () {
        http.get('http://dca-backend.default.svc.cluster.local:8080/backend/api/play');
        sleep(1);
    }