apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: dev
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:               # 워커 노드로 고정
        kubernetes.io/hostname: k3s-worker
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6","run","--out","experimental-prometheus-rw","/scripts/script.js"]
          env:
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
            # Native histogram 끄고 Counter/Gauge만 보냄
            - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
              value: "false"
            # 다양한 통계치 export (Grafana 대시보드 호환용)
            - name: K6_PROMETHEUS_RW_TREND_STATS
              value: "avg,min,max,p(90),p(95),p(99)"
            # 푸시 주기 (짧은 테스트도 반영되도록)
            - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
              value: "2s"
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts