apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "--out", "prometheus", "/scripts/script.js"]
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts