apiVersion: apps/v1
kind: Deployment
metadata:
  name: dca-backend
  namespace: default
  labels:
    app: dca-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dca-backend
  template:
    metadata:
      labels:
        app: dca-backend
    spec:
      serviceAccountName: backend-sa
      imagePullSecrets:
        - name: dockerhub-secret
      nodeSelector:
        node-role: worker   # 워커 노드에만 올라가도록 설정
      containers:
        - name: dca-backend
          image: zlxldgus123/spring-app:latest
          ports:
            - containerPort: 8080