apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      imagePullSecrets: # 🔹 여기서 regcred로 수정
        - name: regcred
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
